FROM python:3.12-slim as requirements

RUN apt-get update && \
    apt-get install -y wget gnupg2 lsb-release && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y procps postgresql-client-17 && \
    apt-get clean

WORKDIR /app
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


FROM requirements

COPY ./apiserver /app/apiserver
COPY ./lib /app/lib
COPY ./main.py /app/main.py
COPY ./learn.py /app/learn.py
COPY ./const.py /app/const.py
COPY ./learn_models /app/learn_models

